### ISSUE TITLE
UserManagement adatbázis réteg

### ISSUE THREAD

**Issue by pmagnucz** [pmagnucz/softproject_test#1]
dao modulba szükség van három package-re: entity, repository, mapper

Entity package-be létre kell hozni két osztályt: CustomerEntity és CompanyEntity. Mind a kettő tartalma meg kell hogy egyezzen a Company és a Customer osztályok tartalmával. Ezen felül egy Long típusú id mező kell mind a kettőbe. JPA annotációkat ne felejtsétek le: osztályra @Entity, id fieldre @Id @GeneratedValue ... stb

Repository: Két interface: CustomerRepository és CompanyRepository. Min a kettő a CrudRepository <Customer/CompanyEntity, Long> osztályból kell hogy származzon. 

Mappar: Company és Customer Mapper osztályok definiálása. 

Kérdés esetén keressetek, de előtte azért nézzetek utána a JPA és a springboot kapcsolatának :D

**Comment by rozgonyilaszlo** [comment]
https://spring.io/guides/gs/accessing-data-jpa/
