### ISSUE TITLE
VehicleManagementServiceImpl

### ISSUE THREAD

**Issue by pmagnucz** [pmagnucz/softproject_test#8]
Ezt osszátok szét egymás között ki mit vállal el belőle. A séma ugyan az mint a UserManagementnél.

- [x] create felelőse: 
- [x] delete felelőse: 
- [ ] getAll felelőse: 
- [x] getById felelőse: 
- [x] update felelőse:

**Comment by zekanysz** [comment]
Este ha tudom holnapra megnézem és megcsinálom a create meg mondjuk delete

**Comment by bottyan94** [comment]
Uh bakker, bocsi megcsináltam most a create, meg getById-t, nem ismerem még annyira a git-et(most vettem észre h írtál ide xd), 
De am asd- branch-ben van, valaki lecsekkolja h jó-e az úgy ? :D köszi

**Comment by zekanysz** [comment]
Jajj Nem baj. Az addNewVehicle-t én is megcsináltam  ugyanígy csináltam csak más nevet adtam ennyi. Szerintem jó. Akkor megpróbálom, ami maradt ha maradt még belőle.

**Comment by zekanysz** [comment]
A maradékot a getAll-t meg az Update-et megcsinálom akkor.
